ci:
  # pre-commit.ci will open PRs updating our hooks once a month
  autoupdate_schedule: monthly
  # skip any check that needs internet access
  autofix_prs: true

repos:
  # Codespell hook configuration
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: Spell Check with Codespell
        args: ['--write-changes', '--ignore-words-list=cppp,normale']
        exclude: 'package-lock\.json|\.svg$'
