import { Jupyter } from "../../projects";

export const coreTeam = [
  {
    completeName: "Thorsten Beier",
    firstName: "Thorsten",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/DerThorsten",
    XLink: "https://twitter.com/ThorstenBeier",
    LinkedInLink:"https://www.linkedin.com/in/thorsten-beier-95b121189/",
    githubName: "@derthorsten",
    avatarRoute: "/img/avatars/Thorsten@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Le Duc Trung",
    firstName: "Trung",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "false",
    githubLink: "https://github.com/trungleduc",
    LinkedInLink:"https://www.linkedin.com/in/ductrung-le/",
    XLink: "",
    githubName: "@trungleduc",
    avatarRoute: "/img/avatars/Trung@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: " Andreas Trawöger",
    firstName: "Andreas",
    position: "DevOps Engineer",
    onGithub: "true",
    onLinkedIn: "false",
    onX: "false",
    githubLink: "https://github.com/atrawog",
    LinkedInLink: "",
    XLink: "",
    githubName: "@atrawog",
    avatarRoute: "/img/avatars/Andreas@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Denisa Checiu",
    firstName: "Denisa",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/DenisaCG",
    LinkedInLink: "https://www.linkedin.com/in/denisa-checiu-georgiana/",
    XLink: "https://twitter.com/DenisaCheciu",
    githubName: "DenisaCheciu",
    avatarRoute: "/img/avatars/Denisa@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Joël Lamotte",
    firstName: "Joel",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "false",
    githubLink: "https://github.com/Klaim",
    LinkedInLink: "https://www.linkedin.com/in/a-jo%C3%ABl-lamotte-a5b09b85/",
    XLink: "",
    githubName: "@Klaim",
    avatarRoute: "/img/avatars/Joel@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Florence Haudin",
    firstName: "Florence",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "false",
    githubLink: "https://github.com/HaudinFlorence",
    LinkedInLink:"https://www.linkedin.com/in/florence-haudin-fr/",
    XLink: "",
    githubName: "@HaudinFlorence",
    avatarRoute: "/img/avatars/Florence@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Nicolas Brichet",
    firstName: "Nicolas",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/brichet",
    LinkedInLink: "https://www.linkedin.com/in/nicolas-brichet-a26369150/",
    XLink: "",
    githubName: "@brichet",
    avatarRoute: "/img/avatars/Nicolas@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Isabel Paredes",
    firstName: "Isabel",
    position: "Robotics Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/ihuicatl",
    LinkedInLink: "https://www.linkedin.com/in/isabel-paredes/",
    XLink: "",
    githubName: "@ihuicatl",
    avatarRoute: "/img/avatars/Isabel@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Gabriela Vives",
    firstName: "Gabriela",
    position: "User Experience Researcher and Designer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/GabrielaVives",
    LinkedInLink: "https://www.linkedin.com/in/gabriela-vives-831ba853/",
    XLink: "",
    githubName: "@GabrielaVives",
    avatarRoute: "/img/avatars/Gabriela@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Hind Montassif",
    firstName: "Hind",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/Hind-M",
    LinkedInLink: "https://www.linkedin.com/in/hindmontassif/",
    XLink: "",
    githubName: "@Hind-M",
    avatarRoute: "/img/avatars/Hind@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Julien Jerphanion",
    firstName: "Julien",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "true",
    githubLink: "https://github.com/jjerphan",
    LinkedInLink: "https://www.linkedin.com/in/jjerphan/",
    XLink: "https://twitter.com/jjerphan",
    githubName: "@jjerphan",
    avatarRoute: "/img/avatars/Julien@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Anutosh Bhat",
    firstName: "Anutosh",
    position: "Scientific Software Development Intern",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/anutosh491",
    LinkedInLink: "https://www.linkedin.com/in/anutosh-bhat-66ba961a8/",
    XLink: "",
    githubName: "@anutosh491",
    avatarRoute: "/img/avatars/Anutosh@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Greg Mooney",
    firstName: "Greg",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/gjmooney",
    LinkedInLink: "https://www.linkedin.com/in/gjmooney/",
    XLink: "",
    githubName: "@gjmooney",
    avatarRoute: "/img/avatars/Greg@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Ian Thomas",
    firstName: "Ian",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/ianthomas23",
    LinkedInLink: "https://www.linkedin.com/in/ian-thomas-796814240/",
    XLink: "",
    githubName: "@ianthomas23",
    avatarRoute: "/img/avatars/Ian@2x.jpg",
    JupyterDistinction: "false"
    
  },
  {
    completeName: "Nour Cheour",
    firstName: "Nour",
    position: " Scientific Software Development Intern",
    onLinkednIn: "true",
    onGithub: "true",
    onX: "false",
    githubLink: "https://github.com/Nour-Cheour10",
    LinkedInLink: "https://www.linkedin.com/in/nour-cheour-606143206/",
    XLink: "",
    githubName: "@Nour-Cheour10",
    avatarRoute: "/img/avatars/Nour@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Meriem Ben Ismail",
    firstName: "Meriem",
    position: " Scientific Software Development Intern",
    onLinkednIn: "true",
    onGithub: "true",
    onX: "false",
    githubLink: "https://github.com/Meriem-BenIsmail",
    LinkedInLink: "https://www.linkedin.com/in/meriem-ben-ismail-163042230/",
    XLink: "",
    githubName: "@Meriem-BenIsmail",
    avatarRoute: "/img/avatars/Meriem@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Alexis Placet",
    firstName: "Alexis",
    position: " Scientific Software Developer",
    onLinkednIn: "true",
    onGithub: "true",
    onX: "false",
    githubLink: "https://github.com/Alex-PLACET",
    LinkedInLink: "https://www.linkedin.com/in/alexisplacet/",
    XLink: "",
    githubName: "@Alex-PLACET",
    avatarRoute: "/img/avatars/Alexis@2x.jpg",
    JupyterDistinction: "false"
  },
  {
    completeName: "Anastasiia Sliusar",
    firstName: "Anastasiia",
    position: " Scientific Software Developer",
    onLinkednIn: "true",
    onGithub: "true",
    onX: "false",
    githubLink: "https://github.com/AnastasiaSliusar",
    LinkedInLink: "https://www.linkedin.com/in/anastasiiasliusar-bellis/",
    XLink: "",
    githubName: "@AnastasiaSliusar",
    avatarRoute: "/img/avatars/Anastasiia@2x.jpg",
    JupyterDistinction: "false"
  },


  
];
export default coreTeam;
