export const leadershipTeam = [
  {
    completeName: "Sylvain Corlay",
    firstName: "Sylvain",
    position: "Chief Executive Officer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/SylvainCorlay",
    LinkedInLink: "https://www.linkedin.com/sylvaincorlay/?locale=en_US",
    XLink: "https://twitter.com/SylvainCorlay",
    githubName: "@SylvainCorlay",
    avatarRoute: "img/avatars/Sylvain@2x.jpg",
    JupyterDistinction: "true",
  },
  {
    completeName: "Johan Mabille",
    firstName: "Johan",
    position: "Project Director",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/JohanMabille",
    LinkedInLink: "https://www.linkedin.com/in/johan-mabille/",
    XLink: "https://twitter.com/JohanMabille",
    githubName: "@JohanMabille",
    avatarRoute: "img/avatars/Johan@2x.jpg",
    JupyterDistinction: "true",
  },
  {
    completeName: "Martin Renou",
    firstName: "Martin",
    position: "Project Director",
    onX: "true",
    onLinkedIn: "true",
    onGithub: "true",
    githubLink: "https://github.com/martinRenou",
    LinkedInLink: "https://www.linkedin.com/in/martin-renou",
    XLink: "https://twitter.com/martinRenou",
    githubName: "@martinRenou",
    avatarRoute: "img/avatars/Martin@2x.jpg",
    JupyterDistinction: "true",
  },
  {
    completeName: "Jeremy Tuloup",
    firstName: "Jeremy",
    position: "Technical Director",
    onLinkedIn: "true",
    onGithub: "true",
    onX: "true",
    githubLink: "https://github.com/jtpio",
    LinkedInLink: "https://www.linkedin.com/in/jtuloup/",
    XLink: "https://twitter.com/jtpio",
    githubName: "@jtpio",
    avatarRoute: "img/avatars/Jeremy@2x.jpg",
    JupyterDistinction: "true",
  },

  {
    completeName: "Afshin Darian",
    firstName: "Darian",
    position: "Technical Director",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "false",
    githubLink: "https://github.com/afshin",
    LinkedInLink: "https://www.linkedin.com/in/afshindarian/",
    XLink: "",
    githubName: "@afshin",
    avatarRoute: "img/avatars/Darian@2x.jpg",
    JupyterDistinction: "true",
  },
  {
    completeName: "David Brochart",
    firstName: "David",
    position: "Technical Director",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/jtpio",
    LinkedInLink: "https://www.linkedin.com/in/david-brochart-4208721/",
    XLink: "https://twitter.com/davidbrochart",
    githubName: "@davidbrochart",
    avatarRoute: "img/avatars/David@2x.jpg",
    JupyterDistinction: "true",
  },
];
export default leadershipTeam;
