import AlexisMD from "@site/src/components/about/Team/Alexis.md";
import AlexisAvatarUrl from "@site/static/img/avatars/Alexis.png";
import AnastasiiaMD from "@site/src/components/about/Team/Anastasiia.md";
import AnastasiiaAvatarUrl from "@site/static/img/avatars/Anastasiia.png";
import AndreasMD from "@site/src/components/about/Team/Andreas.md";
import AndreasAvatarUrl from "@site/static/img/avatars/Andreas.png";
import AntoineMD from "@site/src/components/about/Team/Antoine.md";
import AntoineAvatarUrl from "@site/static/img/avatars/Antoine2.png";
import AnutoshMD from "@site/src/components/about/Team/Anutosh.md";
import AnutoshAvatarUrl from "@site/static/img/avatars/Anutosh.png";
import ArjunMD from "@site/src/components/about/Team/Arjun.md"
import ArjunAvatarUrl from "@site/static/img/avatars/Arjun.png";
import DavidMD from "@site/src/components/about/Team/David.md";
import DavidAvatarUrl from "@site/static/img/avatars/David.png";
import DarianMD from "@site/src/components/about/Team/Darian.md";
import DarianAvatarUrl from "@site/static/img/avatars/Darian.png";
import DenisaMD from "@site/src/components/about/Team/Denisa.md";
import DenisaAvatarUrl from "@site/static/img/avatars/Denisa.png";
import FlorenceMD from "@site/src/components/about/Team/Florence.md";
import FlorenceAvatarUrl from "@site/static/img/avatars/Florence.png";
import GabrielaMD from "@site/src/components/about/Team/Gabriela.md";
import GabrielaAvatarUrl from "@site/static/img/avatars/Gabriela.png";
import GregMD from "@site/src/components/about/Team/Greg.md";
import GregAvatarUrl from "@site/static/img/avatars/Greg.png";
import HindMD from "@site/src/components/about/Team/Hind.md";
import HindAvatarUrl from "@site/static/img/avatars/Hind.png";
import IanMD from "@site/src/components/about/Team/Ian.md";
import IanAvatarUrl from "@site/static/img/avatars/Ian.png";
import IsabelMD from "@site/src/components/about/Team/Isabel.md";
import IsabelAvatarUrl from "@site/static/img/avatars/Isabel.png";
import JeremyMD from "@site/src/components/about/Team/Jeremy.md";
import JeremyAvatarUrl from "@site/static/img/avatars/Jeremy.png";
import JoelMD from "@site/src/components/about/Team/Joel.md";
import JoelAvatarUrl from "@site/static/img/avatars/Joel.png";
import JohanMD from "@site/src/components/about/Team/Johan.md";
import JohanAvatarUrl from "@site/static/img/avatars/Johan.png";
import JulienMD from "@site/src/components/about/Team/Julien.md";
import JulienAvatarUrl from "@site/static/img/avatars/Julien.png";
import MartinMD from "@site/src/components/about/Team/Martin.md";
import MartinAvatarUrl from "@site/static/img/avatars/Martin.png";
import MatthiasMD from "@site/src/components/about/Team/Matthias.md";
import MatthiasAvatarUrl from "@site/static/img/avatars/Matthias.png";
import MeriemMD from "@site/src/components/about/Team/Meriem.md";
import MeriemAvatarUrl from "@site/static/img/avatars/Meriem.png";
import NicolasMD from "@site/src/components/about/Team/Nicolas.md";
import NicolasAvatarUrl from "@site/static/img/avatars/Nicolas.png";
import RomainMD from "@site/src/components/about/Team/Romain.md";
import RomainAvatarUrl from "@site/static/img/avatars/Romain.png";
import SergeMD from "@site/src/components/about/Team/Serge.md";
import SergeAvatarUrl from "@site/static/img/avatars/Serge.png";
import SylvainMD from "@site/src/components/about/Team/Sylvain.md";
import SylvainAvatarUrl from "@site/static/img/avatars/Sylvain.png";
import ThorstenMD from "@site/src/components/about/Team/Thorsten.md";
import ThorstenAvatarUrl from "@site/static/img/avatars/Thorsten.png";
import TrungMD from "@site/src/components/about/Team/Trung.md";
import TrungAvatarUrl from "@site/static/img/avatars/Trung.png";


export const coreTeam = [
  {
    completeName: "Thorsten Beier",
    firstName: "Thorsten",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/DerThorsten",
    XLink: "https://twitter.com/ThorstenBeier",
    LinkedInLink: "https://www.linkedin.com/in/thorsten-beier-95b121189/",
    githubName: "@derthorsten",
    avatarUrl: ThorstenAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: ThorstenMD,
  },
  {
    completeName: "Le Duc Trung",
    firstName: "Trung",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "false",
    githubLink: "https://github.com/trungleduc",
    LinkedInLink: "https://www.linkedin.com/in/ductrung-le/",
    XLink: "",
    githubName: "@trungleduc",
    avatarUrl: TrungAvatarUrl,
    distinctionTitle: ["Jupyter Distinguished Contributor"],
    distinctionLink: ["https://jupyter.org/about#distinguished-contributors"],
    subTeamName: "coreTeam",
    BioComponent: TrungMD,
  },
  {
    completeName: " Andreas Trawöger",
    firstName: "Andreas",
    position: "DevOps Engineer",
    onGithub: "true",
    onLinkedIn: "false",
    onX: "false",
    githubLink: "https://github.com/atrawog",
    LinkedInLink: "",
    XLink: "",
    githubName: "@atrawog",
    avatarUrl: AndreasAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: AndreasMD,
  },
  {
    completeName: "Denisa Checiu",
    firstName: "Denisa",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/DenisaCG",
    LinkedInLink: "https://www.linkedin.com/in/denisa-checiu-georgiana/",
    XLink: "https://twitter.com/DenisaCheciu",
    githubName: "DenisaCheciu",
    avatarUrl: DenisaAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: DenisaMD,
  },
  {
    completeName: "Joël Lamotte",
    firstName: "Joel",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "false",
    githubLink: "https://github.com/Klaim",
    LinkedInLink: "https://www.linkedin.com/in/a-jo%C3%ABl-lamotte-a5b09b85/",
    XLink: "",
    githubName: "@Klaim",
    avatarUrl: JoelAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: JoelMD,
  },
  {
    completeName: "Florence Haudin",
    firstName: "Florence",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "false",
    githubLink: "https://github.com/HaudinFlorence",
    LinkedInLink: "https://www.linkedin.com/in/florence-haudin-fr/",
    XLink: "",
    githubName: "@HaudinFlorence",
    avatarUrl: FlorenceAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: FlorenceMD,
  },
  {
    completeName: "Nicolas Brichet",
    firstName: "Nicolas",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/brichet",
    LinkedInLink: "https://www.linkedin.com/in/nicolas-brichet-a26369150/",
    XLink: "",
    githubName: "@brichet",
    avatarUrl: NicolasAvatarUrl,
    distinctionTitle: ["Jupyter Distinguished Contributor"],
    distinctionLink: ["https://jupyter.org/about#distinguished-contributors"],
    subTeamName: "coreTeam",
    BioComponent: NicolasMD,
  },
  {
    completeName: "Isabel Paredes",
    firstName: "Isabel",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/ihuicatl",
    LinkedInLink: "https://www.linkedin.com/in/isabel-paredes/",
    XLink: "",
    githubName: "@IsabelParedes",
    avatarUrl: IsabelAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: IsabelMD,
  },
  {
    completeName: "Gabriela Vives",
    firstName: "Gabriela",
    position: "User Experience Researcher and Designer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/GabrielaVives",
    LinkedInLink: "https://www.linkedin.com/in/gabriela-vives-831ba853/",
    XLink: "",
    githubName: "@GabrielaVives",
    avatarUrl: GabrielaAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: GabrielaMD,
  },
  {
    completeName: "Hind Montassif",
    firstName: "Hind",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/Hind-M",
    LinkedInLink: "https://www.linkedin.com/in/hindmontassif/",
    XLink: "",
    githubName: "@Hind-M",
    avatarUrl: HindAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: HindMD,
  },
  {
    completeName: "Julien Jerphanion",
    firstName: "Julien",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "true",
    githubLink: "https://github.com/jjerphan",
    LinkedInLink: "https://www.linkedin.com/in/jjerphan/",
    XLink: "https://twitter.com/jjerphan",
    githubName: "@jjerphan",
    avatarUrl: JulienAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: JulienMD,
  },
  {
    completeName: "Anutosh Bhat",
    firstName: "Anutosh",
    position: "Scientific Software Development Intern",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/anutosh491",
    LinkedInLink: "https://www.linkedin.com/in/anutosh-bhat-66ba961a8/",
    XLink: "",
    githubName: "@anutosh491",
    avatarUrl: AnutoshAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: AnutoshMD,
  },
  {
    completeName: "Greg Mooney",
    firstName: "Greg",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/gjmooney",
    LinkedInLink: "https://www.linkedin.com/in/gjmooney/",
    XLink: "",
    githubName: "@gjmooney",
    avatarUrl: GregAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: GregMD,
  },
  {
    completeName: "Ian Thomas",
    firstName: "Ian",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkednIn: "true",
    onX: "false",
    githubLink: "https://github.com/ianthomas23",
    LinkedInLink: "https://www.linkedin.com/in/ian-thomas-796814240/",
    XLink: "",
    githubName: "@ianthomas23",
    avatarUrl: IanAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: IanMD,
  },
  {
    completeName: "Meriem Ben Ismail",
    firstName: "Meriem",
    position: " Scientific Software Development Intern",
    onLinkednIn: "true",
    onGithub: "true",
    onX: "false",
    githubLink: "https://github.com/Meriem-BenIsmail",
    LinkedInLink: "https://www.linkedin.com/in/meriem-ben-ismail-163042230/",
    XLink: "",
    githubName: "@Meriem-BenIsmail",
    avatarUrl: MeriemAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: MeriemMD,
  },
  {
    completeName: "Alexis Placet",
    firstName: "Alexis",
    position: " Scientific Software Developer",
    onLinkednIn: "true",
    onGithub: "true",
    onX: "false",
    githubLink: "https://github.com/Alex-PLACET",
    LinkedInLink: "https://www.linkedin.com/in/alexisplacet/",
    XLink: "",
    githubName: "@Alex-PLACET",
    avatarUrl: AlexisAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: AlexisMD,
  },
  {
    completeName: "Anastasiia Sliusar",
    firstName: "Anastasiia",
    position: " Scientific Software Developer",
    onLinkednIn: "true",
    onGithub: "true",
    onX: "false",
    githubLink: "https://github.com/AnastasiaSliusar",
    LinkedInLink: "https://www.linkedin.com/in/anastasiiasliusar-bellis/",
    XLink: "",
    githubName: "@AnastasiaSliusar",
    avatarUrl: AnastasiiaAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: AnastasiiaMD,
  },
  {
    completeName: "Arjun Verma",
    firstName: "Arjun",
    position: " Scientific Software Development Intern",
    onLinkednIn: "true",
    onGithub: "true",
    onX: "true",
    githubLink: "https://github.com/arjxn-py",
    LinkedInLink:
      "https://www.linkedin.com/in/arjun-verma-758608226/",
    XLink: "https://x.com/ArjxnPy",
    githubName: "@arjxn-py",
    avatarUrl: ArjunAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "coreTeam",
    BioComponent: ArjunMD,
  },
  {
    completeName: "Antoine Pitrou",
    firstName: "Antoine",
    position: " Senior Software Developer",
    onLinkednIn: "true",
    onGithub: "true",
    onX: "false",
    githubLink: "https://github.com/pitrou",
    LinkedInLink:
      "https://www.linkedin.com/in/pitrou/?originalSubdomain=fr",
    XLink: "",
    githubName: "@pitrou",
    avatarUrl: AntoineAvatarUrl,
    distinctionTitle: ["Python Software Foundation Fellow"],
    distinctionLink: ["https://www.python.org/psf/fellows-roster/"],
    subTeamName: "coreTeam",
    BioComponent: AntoineMD,
  },
];

export const QSCollaboratorsTeam = [
  {
    completeName: "Serge Guelton",
    firstName: "Serge",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "false",
    githubLink: "https://github.com/serge-sans-paille",
    LinkedInLink: "",
    XLink: "",
    githubName: "@serge-sans-paille",
    avatarUrl: SergeAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "QSCollaboratorsTeam",
    BioComponent: SergeMD,
  },
  {
    completeName: "Romain Menegaux",
    firstName: "Romain",
    position: "Scientific Software Developer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/rmenegaux",
    LinkedInLink: "https://www.linkedin.com/in/romain-menegaux-88a147134/",
    XLink: "https://twitter.com/RomainMenegaux",
    githubName: "@trmenegaux",
    avatarUrl: RomainAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "QSCollaboratorsTeam",
    BioComponent: RomainMD
  },
];

export const leadershipTeam = [
  {
    completeName: "Sylvain Corlay",
    firstName: "Sylvain",
    position: "Chief Executive Officer",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/SylvainCorlay",
    LinkedInLink: "https://www.linkedin.com/sylvaincorlay/?locale=en_US",
    XLink: "https://twitter.com/SylvainCorlay",
    githubName: "@SylvainCorlay",
    avatarUrl: SylvainAvatarUrl,
    distinctionTitle: ["ACM Software System Award"],
    distinctionLink: ["https://awards.acm.org/award_winners/corlay_8324973"],
    subTeamName: "LeadershipTeam",
    BioComponent: SylvainMD,
  },
  {
    completeName: "Johan Mabille",
    firstName: "Johan",
    position: "Project Director",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/JohanMabille",
    LinkedInLink: "https://www.linkedin.com/in/johan-mabille/",
    XLink: "https://twitter.com/JohanMabille",
    githubName: "@JohanMabille",
    avatarUrl: JohanAvatarUrl,
    distinctionTitle: ["Jupyter Distinguished Contributor"],
    distinctionLink: ["https://jupyter.org/about#distinguished-contributors"],
    subTeamName: "LeadershipTeam",
    BioComponent: JohanMD,
  },
  {
    completeName: "Martin Renou",
    firstName: "Martin",
    position: "Project Director",
    onX: "true",
    onLinkedIn: "true",
    onGithub: "true",
    githubLink: "https://github.com/martinRenou",
    LinkedInLink: "https://www.linkedin.com/in/martin-renou",
    XLink: "https://twitter.com/martinRenou",
    githubName: "@martinRenou",
    avatarUrl: MartinAvatarUrl,
    distinctionTitle: ["Jupyter Distinguished Contributor"],
    distinctionLink: ["https://jupyter.org/about#distinguished-contributors"],
    subTeamName: "LeadershipTeam",
    BioComponent: MartinMD,
  },
  {
    completeName: "Jeremy Tuloup",
    firstName: "Jeremy",
    position: "Technical Director",
    onLinkedIn: "true",
    onGithub: "true",
    onX: "true",
    githubLink: "https://github.com/jtpio",
    LinkedInLink: "https://www.linkedin.com/in/jtuloup/",
    XLink: "https://twitter.com/jtpio",
    githubName: "@jtpio",
    avatarUrl: JeremyAvatarUrl,
    distinctionTitle: ["Jupyter Distinguished Contributor"],
    distinctionLink: ["https://jupyter.org/about#distinguished-contributors"],
    subTeamName: "LeadershipTeam",
    BioComponent: JeremyMD,
  },

  {
    completeName: "Afshin Darian",
    firstName: "Darian",
    position: "Technical Director",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "false",
    githubLink: "https://github.com/afshin",
    LinkedInLink: "https://www.linkedin.com/in/afshindarian/",
    XLink: "",
    githubName: "@afshin",
    avatarUrl: DarianAvatarUrl,
    distinctionTitle: ["Jupyter Distinguished Contributor"],
    distinctionLink: ["https://jupyter.org/about#distinguished-contributors"],
    subTeamName: "LeadershipTeam",
    BioComponent: DarianMD,
  },
  {
    completeName: "David Brochart",
    firstName: "David",
    position: "Technical Director",
    onGithub: "true",
    onLinkedIn: "true",
    onX: "true",
    githubLink: "https://github.com/jtpio",
    LinkedInLink: "https://www.linkedin.com/in/david-brochart-4208721/",
    XLink: "https://twitter.com/davidbrochart",
    githubName: "@davidbrochart",
    avatarUrl: DavidAvatarUrl,
    distinctionTitle: ["Jupyter Distinguished Contributor"],
    distinctionLink: ["https://jupyter.org/about#distinguished-contributors"],
    subTeamName: "LeadershipTeam",
    BioComponent: DavidMD,
  },
  {
    completeName: "Matthias Meschede",
    firstName: "Matthias",
    position: "Director Business Development",
    onGithub: "true",
    onLinkedIn: "true",
    onX: false,
    githubLink: "https://github.com/mmesch",
    LinkedInLink: "https://www.linkedin.com/in/mmesch/",
    githubName: "@mmesch",
    avatarUrl: MatthiasAvatarUrl,
    distinctionTitle: [],
    distinctionLink: [],
    subTeamName: "LeadershipTeam",
    BioComponent: MatthiasMD,
  },
];
