const coreTeam = [
  {
    completeName: "Thorsten Beier",
    firstName: "Thorsten",
    position: "Scientific Software Developer",
    onX: "true",
    onGithub: "true",
    githubLink: "https://github.com/DerThorsten",
    Xlink: "https://twitter.com/ThorstenBeier",
    githubName: "@derthorsten",
    avatarRoute: "img/avatars/Thorsten@2x.jpg",
  },
  {
    completeName: "Le Duc Trung",
    firstName: "Trung",
    position: "Scientific Software Developer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/trungleduc",
    Xlink: "",
    githubName: "@trungleduc",
    avatarRoute: "img/avatars/Trung@2x.jpg",
  },
  {
    completeName: " Andreas Trawöger",
    firstName: "Andreas",
    position: "DevOps Engineer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/atrawog",
    Xlink: "",
    githubName: "@atrawog",
    avatarRoute: "img/avatars/Andreas@2x.jpg",
  },
  {
    completeName: "Denisa Checiu",
    firstName: "Denisa",
    position: "Scientific Software Developer",
    onX: "true",
    onGithub: "true",
    githubLink: "https://github.com/DenisaCG",
    Xlink: "https://twitter.com/DenisaCheciu",
    githubName: "DenisaCheciu",
    avatarRoute: "img/avatars/Denisa@2x.jpg",
  },
  {
    completeName: "Joël Lamotte",
    firstName: "Joel",
    position: "Scientific Software Developer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/Klaim",
    Xlink: "",
    githubName: "@Klaim",
    avatarRoute: "img/avatars/Joel@2x.jpg",
  },
  {
    completeName: "Florence Haudin",
    firstName: "Florence",
    position: "Scientific Software Developer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/HaudinFlorence",
    Xlink: "",
    githubName: "@HaudinFlorence",
    avatarRoute: "img/avatars/Florence@2x.jpg",
  },
  {
    completeName: "Nicolas Brichet",
    firstName: "Nicolas",
    position: "Scientific Software Developer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/brichet",
    Xlink: "",
    githubName: "@brichet",
    avatarRoute: "img/avatars/Nicolas@2x.jpg",
  },
  {
    completeName: "Isabel Paredes",
    firstName: "Isabel",
    position: "Robotics Software Developer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/ihuicatl",
    Xlink: "",
    githubName: "@ihuicatl",
    avatarRoute: "img/avatars/Isabel@2x.jpg",
  },
  {
    completeName: "Gabriela Vives",
    firstName: "Gabriela",
    position: "User Experience Researcher and Designer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/GabrielaVives",
    Xlink: "",
    githubName: "@GabrielaVives",
    avatarRoute: "img/avatars/Gabriela@2x.jpg",
  },
  {
    completeName: "Hind Montassif",
    firstName: "Hind",
    position: "Scientific Software Developer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/Hind-M",
    Xlink: "",
    githubName: "@Hind-M",
    avatarRoute: "img/avatars/Hind@2x.jpg",
  },
  {
    completeName: "Julien Jerphanion",
    firstName: "Julien",
    position: "Scientific Software Developer",
    onX: "true",
    onGithub: "true",
    githubLink: "https://github.com/jjerphan",
    Xlink: "https://twitter.com/jjerphan",
    githubName: "@jjerphan",
    avatarRoute: "img/avatars/Julien@2x.jpg",
  },
  {
    completeName: "Anutosh Bhat",
    firstName: "Anutosh",
    position: "Scientific Software Development Intern",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/anutosh491",
    Xlink: "",
    githubName: "@anutosh491",
    avatarRoute: "img/avatars/Anutosh@2x.jpg",
  },
  {
    completeName: "Greg Mooney",
    firstName: "Greg",
    position: "Scientific Software Development Intern",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/gjmooney",
    Xlink: "",
    githubName: "@gjmooney",
    avatarRoute: "img/avatars/Greg@2x.jpg",
  },
  {
    completeName: "Ian Thomas",
    firstName: "Ian",
    position: "Scientific Software Development Intern",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/ianthomas23",
    Xlink: "",
    githubName: "@ianthomas23",
    avatarRoute: "img/avatars/Ian@2x.jpg",
  },
  {
    completeName: "Nour Cheour",
    firstName: "Nour",
    position: " Scientific Software Development Intern",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/Nour-Cheour10",
    Xlink: "",
    githubName: "@Nour-Cheour10",
    avatarRoute: "img/avatars/Nour@2x.jpg",
  },
  {
    completeName: "Meriem Ben Ismail",
    firstName: "Meriem",
    position: " Scientific Software Development Intern",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/Meriem-BenIsmail",
    Xlink: "",
    githubName: "@Meriem-BenIsmail",
    avatarRoute: "img/avatars/Meriem@2x.jpg",
  },
  {
    completeName: "Alexis Placet",
    firstName: "Alexis",
    position: " Scientific Software Developer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/Alex-PLACET",
    Xlink: "",
    githubName: "@Alex-PLACET",
    avatarRoute: "img/avatars/Alexis@2x.jpg",
  },
  {
    completeName: "Anastasiia Sliusar",
    firstName: "Anastasiia",
    position: " Scientific Software Developer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/AnastasiaSliusar",
    Xlink: "",
    githubName: "@AnastasiaSliusar",
    avatarRoute: "img/avatars/Anastasiia@2x.jpg",
  },


  
];
export default coreTeam;
