const leadershipTeam = [
  {
    completeName: "Sylvain Corlay",
    firstName: "Sylvain",
    position: "Chief Executive Officer",
    onGithub: "true",
    onX: "true",
    githubLink: "https://github.com/SylvainCorlay",
    Xlink: "https://twitter.com/SylvainCorlay",
    githubName: "@SylvainCorlay",
    avatarRoute: "img/avatars/Sylvain@2x.jpg",
  },
  {
    completeName: "Johan Mabille",
    firstName: "Johan",
    position: "Project Director",
    onX: "true",
    onGithub: "true",
    githubLink: "https://github.com/JohanMabille",
    Xlink: "https://twitter.com/JohanMabille",
    githubName: "@JohanMabille",
    avatarRoute: "img/avatars/Johan@2x.jpg",
  },
  {
    completeName: "Martin Renou",
    firstName: "Martin",
    position: "Project Director",
    onX: "true",
    onGithub: "true",
    githubLink: "https://github.com/martinRenou",
    Xlink: "https://twitter.com/martinRenou",
    githubName: "@martinRenou",
    avatarRoute: "img/avatars/Martin@2x.jpg",
  },
  {
    completeName: "Jeremy Tuloup",
    firstName: "Jeremy",
    position: "Technical Director",
    onX: "true",
    onGithub: "true",
    githubLink: "https://github.com/jtpio",
    Xlink: "https://twitter.com/jtpio",
    githubName: "@jtpio",
    avatarRoute: "img/avatars/Jeremy@2x.jpg",
  },

  {
    completeName: "Fanny Loustau-Chartez",
    firstName: "Fanny",
    position: "Chief Financial Officer",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/FannyLoustau",
    Xlink: "",
    githubName: "@FannyLoustau",
    avatarRoute: "img/avatars/Fanny@2x.jpg",
  },
  {
    completeName: "Afshin Darian",
    firstName: "Darian",
    position: "Technical Director",
    onX: "false",
    onGithub: "true",
    githubLink: "https://github.com/afshin",
    Xlink: "",
    githubName: "@afshin",
    avatarRoute: "img/avatars/Darian@2x.jpg",
  },
  {
    completeName: "David Brochart",
    firstName: "David",
    position: "Technical Director",
    onX: "true",
    onGithub: "true",
    githubLink: "https://github.com/jtpio",
    Xlink: "https://twitter.com/davidbrochart",
    githubName: "@davidbrochart",
    avatarRoute: "img/avatars/David@2x.jpg",
  }

];
 export default
  leadershipTeam

